### ISSUE TITLE
Add support for passing defaults to create_resources for system users and rubies

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/puppet-rvm#120]
Can we get a system_rubies_defaults and system_users_defaults to use here?

https://github.com/maestrodev/puppet-rvm/blob/master/manifests/init.pp#L39-L40

**Comment by carlossg** [comment]
Can you submit a PR?

**Comment by ekohl** [comment]
I'm going to close this based on its age. A PR is still welcome.
