### ISSUE TITLE
Allow mouting self hosted binaries

### ISSUE THREAD

**Issue by ayashjorden** [voxpupuli/puppet-rvm#131]
Hello Maestrodev team,
We're using this great module for a long time, thank you for making it :)

We're facing an issue where Ubuntu 15.10 (yes I know it is EOL-ed) doesn't have binaries hosted on rvm.io and we can't compile it on some of our EC2 instances.

Tried to play a little with `rvm prepare` and `rvm mount` but didn't get a useful result.
Also, saw that tag v1.13.1 added the mount option.

How can one self host a packaged ruby binaries and install them (hosted on s3 or other solution)?

Thank you,
Yarden

**Comment by ekohl** [comment]
I'm going to close this based on its age. If you can still reproduce it, please reopen.
