### ISSUE TITLE
Stuck with this module. gpg: Can't check signature:

### ISSUE THREAD

**Issue by sbutt** [voxpupuli/puppet-rvm#134]
Hi,

I'm not sure this is really an "issue" as I'm using a very simple case, and I imagine lots of people would be having the same problem. When using the module and calling puppet apply, it complains about the gpg signature. If I then run the command to add the key, I can then manually run the curl | bash to install RVM which works just fine. However, when I try to run it from the Puppet module again, it complains about the GPG key again. 

Perhaps someone could point me to a better place to ask this question? But I'm stuck as to where to ask. 

Thanks,

Steve

**Comment by sharkannon** [comment]
Make sure you have golja-gnupg  installed or it can't deal with the gpg key :(  (Had the same problem myself)

**Comment by sbutt** [comment]
Yes, that did the trick. Thanks. 👍 

Now, in the interests of automation, how do I get Puppet to blindly do that for me? Rhetotrical question, I can figure that out - Why would you want to "blindly" install a GPG key? Because reasons.  Need to automate all the things.

**Comment by sharkannon** [comment]
Not sure what you mean? When you install the maestrodev/puppet-rvm module using `puppet module install maestrodev/rvm`, it should install the dependencies which includes golja/gnupg, however if you install the maestrodev/puppet-rvm module manually, you'll also have to check the metadata.json file for dependencies and download them as well: 

` "dependencies": [
    {
      "name": "puppetlabs/stdlib",
      "version_requirement": ">=4.2.0"
    },
    {
      "name": "golja/gnupg",
      "version_requirement": ">=1.2.0"
    }
  ],`

**Comment by ekohl** [comment]
I'm going to close this based on its age. If you can still reproduce it, please reopen.
