### ISSUE TITLE
Trying to install ruby 2.3.1 on macos 10.12

### ISSUE THREAD

**Issue by yaron-idan** [voxpupuli/puppet-rvm#135]
I'm using PE 2016.4.2 in order to install rvm on a macos sierra 10.12.3.
rvm is being installed successfully after adding the rvm class to the puppet agent, adding the user I log in with as system_users parameter.

However, when I try to use `rvm_system_ruby` to install ruby-2.3.1 on the agent, puppet fails. Attached is a gist with the output of the puppet configuration failure - https://gist.github.com/yaron-idan/3ed1cdcef27cbbfbd18b39f0109b381a

It seems the class is trying to execute brew as root, although it should run as the user I'm logged in with. I realize I should probably instruct `rvm_system_ruby` to run as the desired user, but can't find how to do it in the documentation.

Is there anything I'm missing here?

**Comment by kdubau** [comment]
Same problem here

**Comment by ekohl** [comment]
I'm going to close this based on its age. If you can still reproduce it, please reopen.
