### ISSUE TITLE
Installing Ruby Fails: cannot set prseent on sure no implict conversion of Hash into string

### ISSUE THREAD

**Issue by james05** [voxpupuli/puppet-rvm#144]
Hi, Trying to install rubies with RVM and always getting stuck with the error:

change from 'absent' to 'present' failed: Could not set 'present' on ensure: no implicit conversion of Hash into String . This happens if I try to install one version of Ruby or any number of versions. The code passes puppet parser validate so the syntax is valid. Any idea on how to fix this?

Thanks!

```
    rvm_system_ruby {
      'ruby-2.5.1':
        ensure      => present,
        proxy_url   => $proxy_url;
      'ruby-2.3.4':
        ensure      => present,
        default_use => true,
        proxy_url   => $proxy_url;
      'ruby-2.4.1':
        ensure      => present,
        default_use => false,
        proxy_url   => $proxy_url;
    }

```

**Comment by ekohl** [comment]
I'm going to close this based on its age. Please reopen this if you can still reproduce the error with the latest version.
