### ISSUE TITLE
Updating rvm signature key

### ISSUE THREAD

**Issue by kyriog** [voxpupuli/puppet-rvm#145]
According to [rvm github](https://github.com/rvm/rvm/issues/4520), the releases are now signed with a new key, which prevents new installations using this puppet rules, as the installer can't verify the new signature.

Could you update the key?

Thanks.

**Comment by TJM** [comment]
You will need to make sure you "select" a key appropriate to the installed version. Good times.

**Comment by kyriog** [comment]
Or the puppet script should import the two keys, so it will be able to manage both old and new versions.
This is, according to the new rvm install guide, the recommended solution.

This script seems to be able to manually install two keys, have a look to [my workaround for PuPHPet](https://github.com/puphpet/puphpet/issues/2830#issuecomment-447345244), but that's a pretty hard-coded way imo.

**Comment by ekohl** [comment]
Addressed in 1c71b55f521cb03020a1e5bf9146b9184c22f6b8
