### ISSUE TITLE
Set --no-document (--no-ri --no-rdoc) option in rvm_gem if gem installed from local sources

### ISSUE THREAD

**Issue by shurab** [voxpupuli/puppet-rvm#40]
We use puppet-rvm to install rvm, ruby, and some gems from already existing gem files.
One of the gem is a legacy one and has broken documentation. In result, output of `gem install gem-with-broken-docs.gem` is always erroneous and puppet-rvm fails as soon as it processes this gem. Unfortunately, we cannot fix it and rebuild gem.
Initially I thought, that I can pass parameter like `--no-documentation` to `rvm_gem`, but `:withopts` param appears does not work for such cases.
A quick look at https://github.com/maestrodev/puppet-rvm/blob/maestrodev/lib/puppet/provider/rvm_gem/gem.rb code shows that in `install` method docs never installed for gem if `:source` param n/a. But in our case, we use `:source` param to point out to gem's location.
A simple code modification will solve issue: 

```
if source = resource[:source]
  # ...
  case uri.scheme
  when nil
    # no URI scheme => interpret the source as a local file
    #command << source
    command << '-N' << source # --no-documentation if local file
  when /file/i
    command << uri.path
  when 'puppet'
    # we don't support puppet:// URLs (yet)
    raise Puppet::Error.new("puppet:// URLs are not supported as gem sources")
  else
    # interpret it as a gem repository
    command << "--source" << "#{source}" << resource[:name]
  end
else
  command << "--no-rdoc" << "--no-ri" <<  resource[:name]
end
```

Also, for consistency, it make sense to disable docs installation for all cases by default. 
Another option is to add install/update options param to rvm_gem type.

**Comment by ekohl** [comment]
I'm going to close this based on its age. If you can still reproduce it, please reopen.
