### ISSUE TITLE
Error: Could not autoload json_backend

### ISSUE THREAD

**Issue by yamiko-ninja** [voxpupuli/puppet-rvm#49]
I am creating a vagrant box for my coworkers. our live server is on centos 6.5 so I am using the puppet box for centos 6.5.

RVM was working for me until I decided to use hiera to configure some settings. I am not using it to configure rvm. Ever since switching I get an error whenever I try to provision the box a second time.

The exact error is `Error: Could not autoload /puppet/pops/binder/hiera2/json_backend: no such file to load -- json`

I looked this up online and read that it is caused because there is no json gem installed.

I added a shell provision to my vagrant file to install the json gem before the puppet provisioner runs. `config.vm.provision "shell", inline: "gem install json"`

Now I get a different kind of error. `/usr/local/rvm/gems/ruby-1.9.3-p547/gems/json-1.8.1/lib/json/ext/parser.so: [BUG] Segmentation fault
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]`

Looks like that is installing the wrong json or is using the wrong ruby. I sshd into the machine as root and removed it and installed it again. When I provision I still get the same error.

you can view my code on bitbucket. I commented out the rvm code since it prevents me from running provision a second time. https://bitbucket.org/yamiko/izanagi/

**Comment by ekohl** [comment]
I'm going to close this based on its age. If you can still reproduce it, please reopen.
