### ISSUE TITLE
rvm::passenger::apache doesn't pass spawnmethod to apache::mod::passenger

### ISSUE THREAD

**Issue by wubr** [voxpupuli/puppet-rvm#97]
While rvm::passenger::apache defines a default for spawnmethod and the docs refer to setting this parameter, I don't see anywhere where it gets passed along to apache::mod::passenger to make it into the actual passenger configuration files.  This might be because puppetlabs-apache didn't support the parameter either, so passing it here wouldn't have done any good.

I've got [changes merged](https://github.com/puppetlabs/puppetlabs-apache/commit/7fffc482b0a5e3d433a21ac96af353e04fb9dc07) into puppetlabs-apache to support spawnmethod, although it hasn't made it into a release yet.  With that in place we should be able to pass the variable and have something actually happen.

**Comment by ekohl** [comment]
I'm going to close this based on its age. If you can still reproduce it, please reopen.
